import views
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^task/(?P<completed_task_id>\d*)$',
        views.task_log,
        name="completed_task_log"),
    url(r'^task/(?P<completed_task_id>\d*)/export$',
        views.task_log_export,
        name="completed_task_log_export"),
    url(r'^task/(?P<completed_task_id>\d*)/workspace_text$',
        views.workspace_text,
        name="completed_task_workspace_text"),
    url(r'^session/(?P<session_id>\d*)$',
        views.session_log,
        name="session_log"),
    url(r'^session/(?P<session_id>\d*)/export$',
        views.session_log_export,
        name="session_log_export"),
    url(r'^session/(?P<session_id>\d*)/(?P<session_group>\d*)$',
        views.session_log,
        name="session_log"),
    url(r'^session/(?P<session_id>\d*)/(?P<session_group>\d*)/export$',
        views.session_log_export,
        name="session_log_export"),
    url(r'^session/(?P<session_id>\d*)/zip-export$',
        views.session_zip_export,
        name="session_zip_export"),
    url(r'^session/(?P<session_id>\d*)/(?P<session_group>\d*)/export_metadata$',
        views.session_metadata_export,
        name="session_metadata_export"),
    url(r'^session/(?P<session_id>\d*)/reset$',
        views.session_reset,
        name="session_reset"),
)
